package com.teamtaskmanager.config;

import com.teamtaskmanager.entity.Project;
import com.teamtaskmanager.entity.ProjectMember;
import com.teamtaskmanager.entity.Task;
import com.teamtaskmanager.entity.User;
import com.teamtaskmanager.enums.ProjectRole;
import com.teamtaskmanager.enums.TaskPriority;
import com.teamtaskmanager.enums.TaskStatus;
import com.teamtaskmanager.repository.ProjectMemberRepository;
import com.teamtaskmanager.repository.ProjectRepository;
import com.teamtaskmanager.repository.TaskRepository;
import com.teamtaskmanager.repository.UserRepository;
import java.time.LocalDate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
public class DataSeeder implements CommandLineRunner {

    private final boolean seedEnabled;
    private final UserRepository userRepository;
    private final ProjectRepository projectRepository;
    private final ProjectMemberRepository projectMemberRepository;
    private final TaskRepository taskRepository;
    private final PasswordEncoder passwordEncoder;

    public DataSeeder(
        @Value("${app.seed.enabled:true}") boolean seedEnabled,
        UserRepository userRepository,
        ProjectRepository projectRepository,
        ProjectMemberRepository projectMemberRepository,
        TaskRepository taskRepository,
        PasswordEncoder passwordEncoder
    ) {
        this.seedEnabled = seedEnabled;
        this.userRepository = userRepository;
        this.projectRepository = projectRepository;
        this.projectMemberRepository = projectMemberRepository;
        this.taskRepository = taskRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    @Transactional
    public void run(String... args) {
        if (!seedEnabled || userRepository.existsByEmail("admin@teamtaskmanager.com")) {
            return;
        }

        User admin = createUser("Admin User", "admin@teamtaskmanager.com", "Admin@12345");
        User member = createUser("Member User", "member@teamtaskmanager.com", "Member@12345");

        Project project = new Project();
        project.setName("Demo Product Launch");
        project.setDescription("Seed project for testing Team Task Manager APIs.");
        project = projectRepository.save(project);

        createMembership(project, admin, ProjectRole.ADMIN);
        createMembership(project, member, ProjectRole.MEMBER);

        createTask(project, admin, "Define launch checklist", TaskStatus.DONE, TaskPriority.HIGH, LocalDate.now().minusDays(2));
        createTask(project, member, "Build Angular dashboard", TaskStatus.IN_PROGRESS, TaskPriority.HIGH, LocalDate.now().plusDays(5));
        createTask(project, member, "Prepare API smoke tests", TaskStatus.TODO, TaskPriority.MEDIUM, LocalDate.now().plusDays(2));
        createTask(project, null, "Review deployment variables", TaskStatus.TODO, TaskPriority.LOW, LocalDate.now().minusDays(1));
    }

    private User createUser(String name, String email, String password) {
        User user = new User();
        user.setName(name);
        user.setEmail(email);
        user.setPassword(passwordEncoder.encode(password));
        return userRepository.save(user);
    }

    private void createMembership(Project project, User user, ProjectRole role) {
        ProjectMember member = new ProjectMember();
        member.setProject(project);
        member.setUser(user);
        member.setRole(role);
        projectMemberRepository.save(member);
    }

    private void createTask(
        Project project,
        User assignee,
        String title,
        TaskStatus status,
        TaskPriority priority,
        LocalDate dueDate
    ) {
        Task task = new Task();
        task.setProject(project);
        task.setAssignee(assignee);
        task.setTitle(title);
        task.setDescription("Demo task generated by backend seed data.");
        task.setStatus(status);
        task.setPriority(priority);
        task.setDueDate(dueDate);
        taskRepository.save(task);
    }
}
